### ISSUE TITLE
Cannot find page problem.

### ISSUE THREAD

**Issue by davidhsu1115** [acbetter/matlab2dash#1]
Hi, 
I have some trouble using this auto-script. It only show cannot find this page in Dash.

**Matlab Version**: R2017a
**Install Path**: /Applications/MATLAB_R2017a.app
**Python Version**: 3.6.1

Thanks for helping.

**Comment by acbetter** [comment]
@davidhsu1115 Have a try to open your MATLAB and open the help documents in your menu bar? It seems that the MATLAB document was not be installed in your computer.

**Comment by acbetter** [comment]
Also, you need to tell me the output of this command `pip3 freeze` to make sure that you have install the python3 package `lxml` and `beautifulsoup4`.

**Comment by acbetter** [comment]
Last, you can send your `*.docset` file which generated by my auto-script for me to debug. My auto-script also has a lot of logs in the console, you can also send to me.

**Comment by acbetter** [comment]
Oh, one more important  thing is whether your computer install other apps whose name contains 'MATLAB'...

**Comment by acbetter** [comment]
Okay, I found the reason. Because of the new version macOS Sierra and new version Dash, the OS symlink can't do it anymore. I will fix the bug.

**Comment by acbetter** [comment]
fixed at [c102d9e](https://github.com/acbetter/matlab2dash/commit/c102d9e3fd42051ce75cde3a75fe339970897d01)

**Comment by davidhsu1115** [comment]
Thanks for you helping, I will try it later today.

From: davidhsu1115@gmail.com
方韋 David Hsu
