### ISSUE TITLE
Docset not creating.

### ISSUE THREAD

**Issue by davidhsu1115** [acbetter/matlab2dash#2]
Sorry to bother again.

I have checked the installation requirement.
The beautifulsoup4, lxml, and pip3 are install properly, and I i am sure the matlab document were install in my local. But the script that I used in terminal.app doesn't generate any Docset that can be used in Dash.

**Comment by davidhsu1115** [comment]
Is there any possibility that you can upload the generated docset, that i can download it

**Comment by acbetter** [comment]
The file is to large... So it's hard for me to upload my docset file (1.6 GB)

Yesterday I packaged a binary file (about 10 MB). You can use it for generating. Have a try!

**Comment by acbetter** [comment]
~~MATLAB Docset Host for Dash will be delete in one week. Please download it soon.~~
